### ISSUE TITLE
Fails to handle type 24

### ISSUE THREAD

**Issue by MrSapps** [stohrendorf/symdump#1]
Just throws an exception:

  throw new Exception("Sodom");

When tested with bio hazard beta 2 symbols.

**Comment by stohrendorf** [comment]
Tried to implement it, can you test it please?

**Comment by MrSapps** [comment]
System.ArgumentException: 'The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Arg_ParamName_Name'


```
  public static string ReadPascalString(this BinaryReader fs)
        {
            var length = fs.ReadByte();
            var result = "";
            while (length-- > 0)
                result += fs.ReadChar();
            return result;
        }
```

on ReadChar()

SymFile attached.

[MAIN.zip](https://github.com/stohrendorf/symdump/files/3538065/MAIN.zip)

Edit: At a random guess perhaps its a Japanese string?

**Comment by stohrendorf** [comment]
I did the first analysis and fixed a few bugs already, but I also encountered a valid non-uniform definition of a struct (`KI2` here), which means I need to do some refactoring to handle this to avoid wrong symbol signatures.

**Comment by stohrendorf** [comment]
It became much more complicated than anticipated. There are some "optimizations" in the debug symbol files that are making things easier for the debugger, but make it more complicated for me to properly restore symbol types. I have a few ideas how to handle this, but I can't tell how long it will take.

**Comment by stohrendorf** [comment]
Should work now, please test.
